export const THEME_MAP: Record<string, string[]> = {
  QBTS: ["Quantum"],
  IONQ: ["Quantum"],
  RGTI: ["Quantum"],
  QUBT: ["Quantum"],
  QMCO: ["Quantum"],
  ARQQ: ["Quantum"],
  AIXI: ["Quantum"],
  NVDA: ["AI Infra"],
  AMD: ["AI Infra"],
  AVGO: ["AI Infra"],
  ARM: ["AI Infra"],
  SMCI: ["AI Infra"],
  DELL: ["AI Infra"],
  META: ["AI Infra"],
  TSM: ["AI Infra"],
  MU: ["AI Infra"],
  VRT: ["AI Infra"],
  ANET: ["AI Infra"],
  MRVL: ["AI Infra"],
  PLTR: ["AI Infra", "Defense"],
  LLY: ["GLP-1"],
  NVO: ["GLP-1"],
  VKTX: ["GLP-1"],
  ALT: ["GLP-1"],
  HIMS: ["GLP-1"],
  AMGN: ["GLP-1"],
  CCJ: ["Nuclear"],
  UEC: ["Nuclear"],
  DNN: ["Nuclear"],
  NXE: ["Nuclear"],
  LEU: ["Nuclear"],
  OKLO: ["Nuclear"],
  SMR: ["Nuclear"],
  NNE: ["Nuclear"],
  CEG: ["Nuclear"],
  UUUU: ["Nuclear", "Rare Earths"],
  MP: ["Rare Earths", "Defense"],
  XOM: ["Oil Shock"],
  CVX: ["Oil Shock"],
  OXY: ["Oil Shock"],
  SLB: ["Oil Shock"],
  HAL: ["Oil Shock"],
  BTU: ["Oil Shock"],
  LMT: ["Defense"],
  RTX: ["Defense"],
  NOC: ["Defense"],
  GD: ["Defense"],
  KTOS: ["Defense"],
  BBAI: ["AI Infra", "Defense"],
  NEM: ["Precious Metals"],
  GOLD: ["Precious Metals"],
  HL: ["Precious Metals"],
  AG: ["Precious Metals"],
  BABA: ["China ADR"],
  BIDU: ["China ADR"],
  JD: ["China ADR"],
  NIO: ["China ADR"],
  XPEV: ["China ADR"],
  LI: ["China ADR"],
  MARA: ["Crypto"],
  RIOT: ["Crypto"],
  COIN: ["Crypto"],
  CLSK: ["Crypto"],
  MSTR: ["Crypto", "AI Infra"],
  HOOD: ["Crypto", "Fintech"],
  WULF: ["Crypto", "AI Infra"],
  IREN: ["Crypto", "AI Infra"],
  SEZL: ["Fintech"],
  AFRM: ["Fintech"],
  UPST: ["Fintech"],
  SOFI: ["Fintech"],
  PYPL: ["Fintech"],
  SQ: ["Fintech"],
  MELI: ["Fintech"],
  RIVN: ["EV"],
  LCID: ["EV"],
  TSLA: ["EV", "AI Infra"],
  ACHR: ["Aviation", "Defense"],
  JOBY: ["Aviation"],
  LUNR: ["Space"],
  RKLB: ["Space"],
  ASTS: ["Space"],
  IRDM: ["Space"],
};

const THEME_PATTERNS: Array<[string, RegExp]> = [
  ["Quantum", /quantum|qubit|rigetti|ionq|d-wave/i],
  ["GLP-1", /glp|obesity|diabetes|lilly|novo|weight loss|mounjaro|wegovy/i],
  ["Nuclear", /nuclear|uranium|reactor|smr|enrichment/i],
  ["Oil Shock", /oil|gas|drilling|energy|petroleum|lng/i],
  ["AI Infra", /artificial|ai|semiconductor|chip|data center|gpu|server/i],
  ["Defense", /defense|aerospace|missile|drone|security/i],
  ["Precious Metals", /gold|silver|mining|metal/i],
  ["Rare Earths", /rare earth|lithium|critical mineral/i],
  ["Biotech", /bio|pharma|therapeutic|medical|drug|fda/i],
  ["China ADR", /china|hong kong|beijing|shanghai/i],
  ["Crypto", /crypto|bitcoin|blockchain|mining/i],
  ["Fintech", /fintech|payments|lending|bank/i],
  ["EV", /electric vehicle|ev battery|charging/i],
  ["Space", /space|satellite|launch|lunar/i],
  ["Aviation", /air taxi|eVTOL|aviation|aircraft/i],
  ["Cyber", /cyber|zero trust|firewall|security/i],
];

export function themeList(ticker: string, name = "", headline = ""): string[] {
  const tk = ticker.toUpperCase();
  const out = new Set<string>(THEME_MAP[tk] ?? []);
  const haystack = `${tk} ${name} ${headline}`;
  for (const [theme, pattern] of THEME_PATTERNS) {
    if (pattern.test(haystack)) out.add(theme);
  }
  return out.size ? [...out] : ["Solo / Unclassified"];
}

export function primaryTheme(ticker: string, name = "", headline = ""): string {
  return themeList(ticker, name, headline)[0] ?? "Solo / Unclassified";
}
