import {signed,number,participationText,memberEvidence} from './packet.mjs';
export const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const direction=value=>typeof value==='number'?(value>0?'up':value<0?'down':''):'';
function link(source){try{const url=new URL(source.url);return url.protocol==='https:'?`<a href="${esc(url.href)}" target="_blank" rel="noopener noreferrer">${esc(source.title)} ↗</a>`:'';}catch{return '';}}
export function eventCard(event){return `<article class="event" data-evidence-id="${esc(event.id)}"><p class="kicker">${esc(event.availableDate)} · ${event.kind==='attribution'?'ATTRIBUTED NARRATIVE':'DOCUMENTED DEVELOPMENT'}</p><h3>${esc(event.title)}</h3><p>${esc(event.summary)}</p>${event.caveat?`<p class="caveat">${esc(event.caveat)}</p>`:''}<div class="sources">${(event.sources||[]).map(link).join('')}</div></article>`;}
function charts(member,packet){return `../memory-replay-20260904/index.html?date=${encodeURIComponent(packet.to)}&ticker=${encodeURIComponent(member.ticker)}`;}
function stockCard(member,packet,expanded){
  const events=memberEvidence(member);
  return `<article class="stock" data-member="${esc(member.ticker)}"><div class="stock-head"><div><p class="kicker">${esc(member.role)}</p><h2>${esc(member.ticker)} <small>${esc(member.name)}</small></h2></div><div class="move ${direction(member.periodPct)}">${esc(signed(member.periodPct))}<small class="muted"><br>comparison move</small></div></div>
  <p>${esc(member.relationship?.summary || 'Company relationship evidence is unavailable by this cutoff.')}</p><div class="sources">${(member.relationship?.sources||[]).map(link).join('')}</div>
  <div class="metrics"><div><small>1D at latest close</small><strong class="${direction(member.after.dayPct)}">${esc(signed(member.after.dayPct))}</strong></div><div><small>Daily BB position</small><strong>${esc(signed(member.after.bbPositionPct))}</strong></div><div><small>D-count · ${esc(member.after.dStatus)}</small><strong>${esc(member.after.dCount ?? 'Unknown')}</strong></div></div>
  <p class="muted">${esc(member.before.session||'No baseline')} close ${esc(number(member.before.close))} → ${esc(member.after.session||'No session')} close ${esc(number(member.after.close))}. ${esc(member.after.band)}.</p>
  <a href="${esc(charts(member,packet))}">Open existing daily chart ↗</a>
  <details${expanded?' open':''}><summary>Context and explanation · ${member.changes.length} new item(s)</summary><p class="muted">${esc(member.explanationState)}. Developments are not a complete causal explanation of the move.</p>${events.map(eventCard).join('')||'<p>No reviewed explanation available in this source set.</p>'}<p class="gaps">${member.unknowns.map(esc).join(' ')}</p></details></article>`;
}
function coverage(packet){return `<section class="panel"><h2>What remains unknown</h2><p>${packet.coverage.compared}/${packet.coverage.candidates} candidate comparisons · ${esc(packet.coverage.sourceState.replaceAll('_',' '))}.</p><p class="gaps">${esc(packet.membership.explanation)}</p><p>Unavailable: ${packet.coverage.unavailableLanes.map(esc).join('; ')}.</p><p class="muted">BB position: 0% is the lower band; 100% the upper band. D-count uses the existing doctrine, including lower-bound readings. Neither is a trade instruction.</p><details><summary>Source limits and excluded evidence</summary><ul>${packet.limitations.map(item=>`<li>${esc(item)}</li>`).join('')}${packet.coverage.exclusions.map(item=>`<li>${esc(item.id||'Unidentified item')}: ${esc(item.reason)}</li>`).join('')}</ul></details></section>`;}
export function renderPacket(packet,mode='changes'){
  const summary=`<section class="summary" aria-label="Fast scan">${packet.summary.map(line=>`<div class="panel"><p>${esc(line)}</p></div>`).join('')}</section><section class="panel"><h2>Where extension is spreading</h2>${participationText(packet).map(line=>`<p>${esc(line)}</p>`).join('')}<p class="muted">Measured retrospective candidates, not a proven historical theme roster. Missing members are not counted as inside the bands.</p></section>`;
  const events=packet.newEvidence.map(eventCard).join('')||'<p>No newly available reviewed developments in this comparison. This is not evidence that nothing happened.</p>';
  const stocks=packet.members.map((m,i)=>stockCard(m,packet,mode==='brief'&&i<2)).join('');
  if(mode==='brief') return `<div class="brief"><p class="kicker">REPLAY BRIEF · ${esc(packet.from)} → ${esc(packet.to)}</p>${summary}<section class="panel"><h2>Market-moving developments in this source set</h2>${events}</section><h2>Stocks in context</h2><p class="muted">Largest absolute comparison moves first. Their explanations open by default; every candidate remains available. No inferred trade ranking.</p>${stocks}${coverage(packet)}</div>`;
  return `${summary}<div class="grid"><section class="panel"><h2>What changed while you were away</h2><p class="muted">Newly available evidence between ${esc(packet.from)} and ${esc(packet.to)}.</p>${events}</section><section><h2>The basket, member by member</h2>${stocks}</section></div>${coverage(packet)}`;
}
