import {buildCoveragePacket} from './coverage/coverage.mjs';
import {buildLifecycleView,compareQuietHistory} from './lifecycle/lifecycle.mjs';
import {esc} from './render.mjs';
import {signed} from './packet.mjs';
let assets;
export async function renderResearchChecks(cutoff){
  assets ||= Promise.all(['coverage/fixtures.json','lifecycle/fixture.json','catalysts/research-report.json'].map(async path=>{
    const response=await fetch(new URL(path,import.meta.url));if(!response.ok)throw Error('Local research asset unavailable: '+path);return response.json();
  })).catch(error=>{assets=null;throw error;});
  return renderCheckModels(...await assets,cutoff);
}
export function renderCheckModels(coverageFixture,lifecycleFixture,catalysts,cutoff=lifecycleFixture.cutoff){
  const coverage=buildCoveragePacket(coverageFixture.input,coverageFixture.cutoff);
  const lifecycle=buildLifecycleView(lifecycleFixture.lifecycleEvents,cutoff);
  const quiet=compareQuietHistory(lifecycleFixture.quietHistory);
  const options=[...new Set([...lifecycleFixture.lifecycleEvents.map(e=>e.at),lifecycleFixture.cutoff])].sort((a,b)=>Date.parse(a)-Date.parse(b));
  return `<p class="notice">SYNTHETIC TEST SCENARIOS — fictional names, headlines, moves and lifecycle decisions. These are inspectable software checks, not market research or live rules.</p>
  <section class="panel"><h2>Coverage: nothing silently falls out</h2><p>${coverage.denominators.sourceRecords.submitted} submitted records → ${coverage.denominators.sourceRecords.included} included records → ${coverage.candidates.length} unique candidates. ${coverage.denominators.sourceRecords.malformed} malformed; ${coverage.denominators.sourceRecords.futureExcluded} future-excluded.</p><p class="muted">Synthetic packet cutoff ${esc(coverage.asOfCutoff)}. This is the supplied candidate union, not whole-market coverage.</p>
  <p>${coverage.laneCoverage.lanes.map(lane=>`<span class="tag">${esc(lane.id)}: ${esc(lane.state)} (${lane.includedRecords}/${lane.submittedRecords})</span>`).join('')}</p>
  <div class="scroll"><table><caption>Every candidate, including unsampled names and unexplained outliers</caption><thead><tr><th>NAME / MEMBERSHIP</th><th>OBSERVED MOVES / WINDOWS</th><th>EXPLANATION</th><th>SOURCE ORIGINS</th></tr></thead><tbody>${coverage.candidates.map(c=>`<tr><th scope="row">${esc(c.symbol)}<br><small>${esc(c.disposition.replaceAll('_',' '))}</small></th><td>${c.moveObservations.length?c.moveObservations.map(m=>`${esc(signed(m.percent))} · ${esc(m.window.label)}<br><small>${esc(m.window.end)} / ${esc(m.lane)}</small>`).join('<br>'):'Unsampled / unavailable — not zero'}</td><td>${c.hasUnexplainedOutlier?'<strong class="gaps">Outlier explanation still needed</strong><br>':''}${c.explanationObservations.map(e=>`${esc(e.state.replaceAll('_',' '))}${e.summary?': '+esc(e.summary):''}`).join('<br>')}</td><td>${c.sourceOrigins.map(o=>`${esc(o.lane)} · ${esc(o.laneState)}`).join('<br>')}</td></tr>`).join('')}</tbody></table></div>
  <details><summary>Record disposition audit</summary><ul>${coverage.recordDispositions.map(r=>`<li>${esc(r.sourceRecordId)} · ${esc(r.status)}${r.reason?' · '+esc(r.reason):''}</li>`).join('')}</ul></details></section>
  <section class="panel"><div class="section-head"><h2>Theme lifecycle: leave the board, keep the history</h2><label>Synthetic checkpoint<select id="lifecycle-cutoff">${options.map(at=>`<option value="${esc(at)}"${at===cutoff?' selected':''}>${esc(at)}</option>`).join('')}</select></label></div>
  <p class="muted">Explicit scenario decisions only. No automatic retirement thresholds. Feed failures never change lifecycle. ${lifecycle.history.length} events retained through this checkpoint.</p>
  <div class="grid">${lifecycle.themes.map(t=>`<article class="stock"><p class="kicker">${esc(t.lifecycle)} · FEED ${esc(t.feed.status)}</p><h3>${esc(t.displayName)}</h3><small>Stable ID: ${esc(t.themeId)}</small><p>${esc(t.lifecycleReason)}</p><p>Current members: ${t.members.map(m=>esc(m.ticker)).join(', ')||'None in this scenario'}</p><details><summary>Full retained history · ${t.history.length} events</summary><ol>${t.history.map(e=>`<li><strong>${esc(e.at)} · ${esc(e.type)}</strong><br>${esc(e.reason)}</li>`).join('')}</ol></details></article>`).join('')}</div></section>
  <section class="panel"><h2>Quiet is not just a small basket move</h2><p class="muted">Separate synthetic comparison; not tied to the lifecycle checkpoint above. Existing prior-session 1.5% approximation versus dated member-band coverage. No live logic changed.</p>
  <div class="scroll"><table><thead><tr><th>SYNTHETIC SESSION</th><th>BASKET</th><th>OUTSIDE / MEASURED / EXPECTED</th><th>MOVE-ONLY READ</th><th>COVERAGE-AWARE READ</th></tr></thead><tbody>${quiet.rows.map(r=>`<tr><td>${esc(r.date)}${r.sessionRole==='today'?' · scenario today':''}</td><td>${esc(signed(r.basketMovePct))}</td><td>${r.outsideBandCensus.outsideBandCount??'?'} / ${r.outsideBandCensus.membersMeasured??'?'} / ${r.outsideBandCensus.membersExpected??'?'}</td><td>${esc(r.existingApproximation)}</td><td>${esc(r.fullVerdict)} · ${esc(r.fullReason)}</td></tr>`).join('')}</tbody></table></div><p class="gaps">Scenario today: ${esc(quiet.todayProtection.status)}. A quiet streak is ${quiet.todayProtection.allowsQuietStreak?'permitted by this comparison':'not established'}.</p></section>
  <section class="panel"><h2>Catalyst stress tests: what actually failed</h2><p class="notice">${esc(catalysts.notice)} Passing tests reproduce current behavior; they do not mean the documented bug is fixed.</p>${catalysts.observations.map(o=>`<article class="event"><p class="kicker">${esc(o.classification.replaceAll('_',' '))} · ${esc(o.desiredContractStatus)}</p><h3>${esc(o.uiLabel)}</h3><p>${esc(o.observation)}</p>${o.counterexample?`<p class="muted">“${esc(o.counterexample.eventA)}” versus “${esc(o.counterexample.eventB)}”</p>`:''}${o.qualification?`<p class="gaps">${esc(o.qualification)}</p>`:''}${o.omissions?.length?`<p class="muted">${o.omissions.map(esc).join(' ')}</p>`:''}</article>`).join('')}<p>No production clustering, source acquisition, lifecycle or morning-delivery change was applied.</p></section>`;
}
